# Generated by Django 3.1 on 2020-08-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=70)),
                ('apelido', models.CharField(max_length=20)),
                ('obs', models.CharField(max_length=100)),
            ],
        ),
    ]
