# Generated by Django 3.1 on 2020-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='apelido',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='obs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
