# Generated by Django 3.1 on 2020-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20200827_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='apelido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
