# Generated by Django 3.1 on 2020-08-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20200827_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=70, null=True, unique=True),
        ),
    ]
