# Generated by Django 3.1 on 2020-08-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20200827_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.EmailField(default='', max_length=70, unique=True),
        ),
    ]
