# Generated by Django 3.1 on 2020-08-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20200827_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
